/*
=================================================
Project 03 - SQL Business Analysis

File:
01_top_customers.sql

Purpose:
Identify the customers who generate the highest
revenue for the company.

Author:
Martin Panelo
=================================================
*/

-- Business Question:
-- Which 10 customers generate the highest revenue?

SELECT
    c.CustomerID,
    c.CompanyName,
    SUM(
        od.UnitPrice
        * od.Quantity
        * (1 - od.Discount)
    ) AS TotalRevenue
FROM Customers AS c
INNER JOIN Orders AS o
    ON c.CustomerID = o.CustomerID
INNER JOIN "Order Details" AS od
    ON o.OrderID = od.OrderID
GROUP BY
    c.CustomerID,
    c.CompanyName
ORDER BY TotalRevenue DESC
LIMIT 10;

-- Business Insight:
-- B's Beverages is the highest-revenue customer,
-- generating 6,154,115.34 in total revenue.
-- The ranking is based on net revenue after discounts.

-- Business Question:
-- What percentage of total revenue is generated by the top 10 customers?

WITH CustomerRevenue AS (
    SELECT
        c.CustomerID,
        c.CompanyName,
        SUM(
            od.UnitPrice
            * od.Quantity
            * (1 - od.Discount)
        ) AS TotalRevenue
    FROM Customers AS c
    INNER JOIN Orders AS o
        ON c.CustomerID = o.CustomerID
    INNER JOIN "Order Details" AS od
        ON o.OrderID = od.OrderID
    GROUP BY
        c.CustomerID,
        c.CompanyName
),

Top10Revenue AS (
    SELECT
        SUM(TotalRevenue) AS RevenueFromTop10
    FROM (
        SELECT
            TotalRevenue
        FROM CustomerRevenue
        ORDER BY TotalRevenue DESC
        LIMIT 10
    )
)

SELECT
    ROUND(
        Top10Revenue.RevenueFromTop10
        * 100.0
        / SUM(CustomerRevenue.TotalRevenue),
        2
    ) AS Top10RevenuePercentage
FROM CustomerRevenue
CROSS JOIN Top10Revenue;

-- Business Insight:
-- The top 10 customers generate 12.46% of the company's
-- total revenue.
-- Revenue is therefore relatively well distributed across
-- the customer base rather than concentrated in only a few clients.

