/*
=================================================
Project 03 - SQL Business Analysis

File:
02_product_performance.sql

Purpose:
Analyze product performance based on revenue.

Author:
Martin Panelo
=================================================
*/


-- =====================================================
-- Business Question 1
-- Which 10 products generate the highest revenue?
-- =====================================================


-- =====================================================
-- STEP 1 - Define the desired output
-- =====================================================
--
-- In this case:
-- 1. The product identifier (ProductID)
-- 2. The product name (ProductName)
-- 3. The total revenue generated by each product
--
-- Revenue is calculated as:
-- UnitPrice × Quantity × (1 - Discount)

SELECT
    p.ProductID,
    p.ProductName,
    SUM(
        od.UnitPrice
        * od.Quantity
        * (1 - od.Discount)
    ) AS TotalRevenue


-- =====================================================
-- STEP 2 - Choose the starting table
-- =====================================================
--
-- We start from the Products table because
-- we want one final row for each product.

FROM Products AS p


-- =====================================================
-- STEP 3 - Connect the required tables
-- =====================================================

-- JOIN connects the Products table with Order Details.
--
-- Products contains descriptive information
-- (ProductName, Category, etc.).
--
-- Order Details contains the sales information
-- (Quantity, UnitPrice and Discount).
--
-- Both tables are related through ProductID.

INNER JOIN "Order Details" AS od
    ON p.ProductID = od.ProductID


-- =====================================================
-- STEP 4 - Aggregate by product
-- =====================================================

-- GROUP BY tells SQL to combine all rows
-- belonging to the same product.
--
-- After creating those groups,
-- SUM() calculates the total revenue
-- for each individual product.
--
-- We group by ProductID because it is
-- the unique identifier of each product.
-- ProductName is included for compatibility
-- with most SQL database engines.

GROUP BY
    p.ProductID,
    p.ProductName


--- =====================================================
-- STEP 5 - Sort by revenue
-- =====================================================

-- ORDER BY sorts the results.
--
-- DESC means:
-- highest revenue first.

ORDER BY
    TotalRevenue DESC


-- =====================================================
-- STEP 6 - Return only the Top 10
-- =====================================================

-- LIMIT returns only the first
-- 10 rows of the ranking.

LIMIT 10;

-- =====================================================
-- Business Question 2
-- Which 10 products sell the highest number of units?
-- =====================================================

SELECT
    p.ProductID,
    p.ProductName,
    SUM(od.Quantity) AS TotalUnitsSold

FROM Products AS p

INNER JOIN "Order Details" AS od
    ON p.ProductID = od.ProductID

GROUP BY
    p.ProductID,
    p.ProductName

ORDER BY
    TotalUnitsSold DESC

LIMIT 10;

-- =====================================================
-- Business Insight
-- =====================================================
-- Louisiana Hot Spiced Okra is the best-selling product
-- by units sold, with more than 206,000 units sold.
--
-- This ranking differs from the revenue ranking,
-- showing that products with the highest sales volume
-- are not necessarily the ones generating the highest revenue.
--
-- Managers should analyze both metrics together when
-- making pricing and inventory decisions.

-- =====================================================
-- Business Question 3
-- Which products appear in the highest number of orders?
-- =====================================================

SELECT
    p.ProductID,
    p.ProductName,
    COUNT(DISTINCT od.OrderID) AS TotalOrders

FROM Products AS p

INNER JOIN "Order Details" AS od
    ON p.ProductID = od.ProductID

GROUP BY
    p.ProductID,
    p.ProductName

ORDER BY
    TotalOrders DESC

LIMIT 10;

-- =====================================================
-- Business Insight
-- =====================================================
-- Finding:
-- Louisiana Hot Spiced Okra appears in the highest
-- number of customer orders (8,040 orders).
--
-- Interpretation:
-- Products with high order frequency may indicate
-- consistent customer demand and should be monitored
-- for inventory availability.
--
-- Business Value:
-- This metric helps inventory planning, demand
-- forecasting and purchasing decisions.

-- =====================================================
-- Business Question 4
-- Which 10 products generate the lowest revenue?
-- =====================================================

SELECT
    p.ProductID,
    p.ProductName,
    SUM(
        od.UnitPrice
        * od.Quantity
        * (1 - od.Discount)
    ) AS TotalRevenue

FROM Products AS p

INNER JOIN "Order Details" AS od
    ON p.ProductID = od.ProductID

GROUP BY
    p.ProductID,
    p.ProductName

ORDER BY
    TotalRevenue ASC

LIMIT 10;

-- =====================================================
-- Business Insight
-- =====================================================
-- Finding:
-- The products at the bottom of the revenue ranking
-- contribute the least to total company revenue.
--
-- Interpretation:
-- Low-revenue products may indicate limited customer
-- demand, low sales volume or pricing issues.
--
-- Business Value:
-- This analysis helps identify products that may require
-- promotional actions, pricing reviews or inventory
-- optimization decisions.

-- ===================================================== 
-- Business Question 5 -- Which products have never been sold? 
-- =====================================================

SELECT
    p.ProductID,
    p.ProductName

FROM Products AS p

LEFT JOIN "Order Details" AS od
    ON p.ProductID = od.ProductID

WHERE
    od.OrderID IS NULL

-- =====================================================
-- Business Insight
-- =====================================================
-- Finding:
-- Every product in the catalog appears
-- at least once in historical sales.

--
-- Business Value:
-- The current product catalog does not
-- contain inactive products based on the
-- available sales history.
--
-- Interpretation:
-- Every product in the catalog appears at least once
-- in the Order Details table.
--
-- Business Value:
-- The current catalog does not contain completely
-- inactive products based on the available sales history.